name: dartboy
description: Multiplatform Gameboy Color emulator using dart and flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  wave_generator: ^0.1.0
  audioplayers: ^3.0.1
  file: ^6.1.4
  file_picker: ^5.2.6
  image: ^4.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
