name: dartboy
description: Dart flutter cross platform game boy emulator

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  wave_generator: 0.1.0
  audioplayers: ^0.8.0
  file_picker: ^1.3.7
  image: ^2.1.4
#  flutter_web: any
#  flutter_web_ui: any

dev_dependencies:
  flutter_test:
    sdk: flutter
#  build_runner: ^1.1.2
#  build_web_compilers: ^1.0.0

flutter:
  uses-material-design: true

#dependency_overrides:
#  flutter_web:
#    git:
#      url: https://github.com/flutter/flutter_web
#      path: packages/flutter_web
#  flutter_web_ui:
#    git:
#      url: https://github.com/flutter/flutter_web
#      path: packages/flutter_web_ui